backend:
  name: git-gateway
  branch: master

display_url: https://decoy-school-test-site.netlify.com

media_folder: /src/static/uploads
public_folder: /uploads

collections:
  - label: "Main Pages"
    name: main-pages
    files:
      - label: "Home Page"
        name: index
        file: src/main-pages/index.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: layout, name: layout, widget: hidden }
          - { label: permalink, name: permalink, widget: hidden }
          - { label: body, name: body, widget: markdown }
      - label: "404"
        name: "404"
        file: src/main-pages/404.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: permalink, name: permalink, widget: hidden }
          - {
              label: eleventyExcludeFromCollections,
              name: eleventyExcludeFromCollections,
              widget: hidden,
            }
          - { label: body, name: body, widget: markdown }
      - label: "About Us"
        name: about-us
        file: src/main-pages/about-us.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: layout, name: layout, widget: hidden }
          - { label: body, name: body, widget: markdown }
          - label: links
            name: links
            widget: list
            fields:
              - { label: text, name: text, widget: string }
              - { label: address, name: address, widget: string }
      - label: "Contact"
        name: contact
        file: src/main-pages/contact.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
      - label: "Information"
        name: information
        file: src/main-pages/information.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: layout, name: layout, widget: hidden }
          - { label: body, name: body, widget: markdown }
          - label: links
            name: links
            widget: list
            fields:
              - { label: text, name: text, widget: string }
              - { label: address, name: address, widget: string }
      - label: "Parents"
        name: parents
        file: src/main-pages/parents.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: layout, name: layout, widget: hidden }
          - { label: body, name: body, widget: markdown }
          - label: links
            name: links
            widget: list
            fields:
              - { label: text, name: text, widget: string }
              - { label: address, name: address, widget: string }
  - name: about-us
    label: "About Us"
    files:
      - label: "Curriculum"
        name: curriculum
        file: src/about-us/curriculum.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
      - label: "Staff"
        name: staff
        file: src/about-us/staff.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
      - label: "Vacancies"
        name: vacancies
        file: src/about-us/vacancies.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
      - label: "Values"
        name: values
        file: src/about-us/values.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
      - label: "Governors"
        name: governors
        file: src/about-us/governors.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
          - label: people
            name: people
            widget: list
            fields:
              - { label: Description, name: description, widget: string }
              - { label: Picture, name: picture, widget: image }
  - name: information
    label: Information
    files:
      - label: "Policies"
        name: policies
        file: src/information/policies.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: layout, name: layout, widget: hidden }
          - { label: body, name: body, widget: markdown }
          - label: links
            name: links
            widget: list
            fields:
              - { label: text, name: text, widget: string }
              - { label: address, name: address, widget: string }
      - label: "Pupil Premium"
        name: pupil-premium
        file: src/information/pupil-premium.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
      - label: "SEND"
        name: send
        file: src/information/send.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
      - label: "Term Dates"
        name: term-dates
        file: src/information/term-dates.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
  - name: parents
    label: Parents
    folder: src/parents
    create: false
    fields:
      - { label: title, name: title, widget: string }
      - { label: body, name: body, widget: markdown }
  - name: curricula
    label: Curricula
    folder: src/curricula
    create: false
    fields:
      - { label: title, name: title, widget: string }
      - { label: body, name: body, widget: markdown }
