backend:
  name: git-gateway
  branch: master

display_url: https://www.decoyschool.co.uk

media_folder: /src/static/uploads
public_folder: /uploads

collections:
  - label: "Main Pages"
    name: main-pages
    files:
      - label: "Home Page"
        name: index
        file: src/main-pages/index.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: layout, name: layout, widget: hidden }
          - { label: permalink, name: permalink, widget: hidden }
          - { label: body, name: body, widget: markdown }
      - label: "404"
        name: "404"
        file: src/main-pages/404.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: permalink, name: permalink, widget: hidden }
          - {
              label: eleventyExcludeFromCollections,
              name: eleventyExcludeFromCollections,
              widget: hidden,
            }
          - { label: body, name: body, widget: markdown }
      - label: "About Us"
        name: about-us
        file: src/main-pages/about-us.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: layout, name: layout, widget: hidden }
          - { label: body, name: body, widget: markdown }
          - label: links
            name: links
            widget: list
            fields:
              - { label: text, name: text, widget: string }
              - { label: address, name: address, widget: string }
      - label: "Contact"
        name: contact
        file: src/main-pages/contact.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
      - label: "COVID-19"
        name: covid-19
        file: src/main-pages/COVID-19.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
          - label: "COVID-19 Documents"
            name: documents
            widget: list
            fields:
              - { label: "Document name", name: name, widget: string }
              - { label: "Document", name: path, widget: file }
      - label: "Information"
        name: information
        file: src/main-pages/information.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: layout, name: layout, widget: hidden }
          - { label: body, name: body, widget: markdown }
          - label: links
            name: links
            widget: list
            fields:
              - { label: text, name: text, widget: string }
              - { label: address, name: address, widget: string }
          - label: "Documents"
            name: documents
            widget: list
            fields:
              - { label: "Document name", name: "name", widget: "string" }
              - { label: "Document", name: "path", widget: "file" }
      - label: "Parents"
        name: parents
        file: src/main-pages/parents.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: layout, name: layout, widget: hidden }
          - { label: body, name: body, widget: markdown }
          - label: links
            name: links
            widget: list
            fields:
              - { label: text, name: text, widget: string }
              - { label: address, name: address, widget: string }
  - name: about-us
    label: "About Us"
    files:
      - label: "Curriculum"
        name: curriculum
        file: src/about-us/curriculum.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
      - label: "Staff"
        name: staff
        file: src/about-us/staff.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
      - label: "Vacancies"
        name: vacancies
        file: src/about-us/vacancies.md
        fields:
          - { label: title, name: title, widget: string }
          - label: "Vacancies"
            name: vacancies
            widget: list
            fields:
              - label: Title
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
              - label: "Documents"
                name: documents
                widget: list
                fields:
                  - { label: "Document name", name: "name", widget: "string" }
                  - { label: "Document", name: "path", widget: "file" }
      - label: "Values"
        name: values
        file: src/about-us/values.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
      - label: "Governors"
        name: governors
        file: src/about-us/governors.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
          - label: "General Documents"
            name: documents
            widget: list
            fields:
              - { label: "Document name", name: name, widget: string }
              - { label: "Document", name: path, widget: file }
          - label: "Terms of Reference Documents"
            name: termsOfReference
            widget: list
            fields:
              - {
                  label: "Term of reference name",
                  name: "name",
                  widget: "string",
                }
              - {
                  label: "Terms of reference document",
                  name: "path",
                  widget: "file",
                }
          - label: "Minutes"
            name: minutes
            widget: list
            add_to_top: true
            label_singular: "committee"
            fields:
              - { label: Committee, name: committee, widget: string }
              - label: Documents
                name: documents
                widget: list
                add_to_top: true
                fields:
                  - { label: Minutes Name, name: name, widget: string }
                  - { label: Minutes Document, name: path, widget: file }
      - name: "Meet the Governors"
        name: "meet the governors"
        file: src/about-us/meet-the-governors.md
        fields:
          - label: "People"
              name: people
              widget: list
              fields:
                - { label: Title, name: title, widget: string }
                - { label: Picture, name: picture, widget: image }
                - { label: Bio, name: bio, widget: markdown, buttons: [bold, italic], minimal: true}

  - name: information
    label: Information
    files:
      - label: "Policies"
        name: policies
        file: src/information/policies.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: layout, name: layout, widget: hidden }
          - { label: body, name: body, widget: markdown }
          - label: "Policy Documents"
            name: policies
            widget: list
            fields:
              - { label: "Policy name", name: "name", widget: "string" }
              - { label: "Policy document", name: "path", widget: "file" }
      - label: "Pupil Premium"
        name: pupil-premium
        file: src/information/pupil-premium.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
          - label: "Policy Documents"
            name: policies
            widget: list
            fields:
              - { label: "Policy name", name: "name", widget: "string" }
              - { label: "Policy document", name: "path", widget: "file" }
      - label: "SEND"
        name: send
        file: src/information/send.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
      - label: "British Values"
        name: "british values"
        file: src/information/british-values.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
      - label: "Term Dates"
        name: term-dates
        file: src/information/term-dates.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
          - label: "Term Date Documents"
            name: documents
            widget: list
            fields:
              - { label: "Year", name: "name", widget: "string" }
              - { label: "Term Dates Document", name: "path", widget: "file" }
  - name: parents
    label: Parents
    files:
      - label: Admissions
        name: admissions
        file: src/parents/admissions.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
      - label: Breakfast & After School Club
        name: basc
        file: src/parents/basc.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
      - label: Extra-Curricular Activities
        name: extra-curricular
        file: src/parents/extra-curricular.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
      - label: Letters to Parents
        name: letters-to-parents
        file: src/parents/letters-to-parents.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
      - label: Nursery
        name: nursery
        file: src/parents/nursery.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
          - label: "Nursery Documents"
            name: documents
            widget: list
            fields:
              - { label: "Document title", name: "name", widget: "string" }
              - { label: "Nursery document", name: "path", widget: "file" }
      - label: Safeguarding
        name: safeguarding
        file: src/parents/safeguarding.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
          - label: "General Documents"
            name: general
            widget: list
            fields:
              - { label: "Document title", name: "name", widget: "string" }
              - { label: "General document", name: "path", widget: "file" }
          - label: "Bullying Resources"
            name: bullying
            widget: list
            fields:
              - { label: "Document title", name: "name", widget: "string" }
              - { label: "Bullying document", name: "path", widget: "file" }
      - label: School Meals
        name: school-meals
        file: src/parents/school-meals.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
      - label: School Uniform
        name: school-uniform
        file: src/parents/school-uniform.md
        fields:
          - { label: title, name: title, widget: string }
          - { label: body, name: body, widget: markdown }
  - name: curricula
    label: Curricula
    folder: src/curricula
    create: false
    fields:
      - { label: title, name: title, widget: string }
      - { label: body, name: body, widget: markdown }
      - label: "Curricular Documents"
        name: documents
        widget: list
        fields:
          - { label: "Document title", name: "name", widget: "string" }
          - { label: "Curriculum document", name: "path", widget: "file" }
  - name: letters
    label: Letters to Parents
    folder: src/letters
    create: false
    fields:
      - { label: title, name: title, widget: string }
      - label: "Letters"
        name: letters
        widget: list
        fields:
          - { label: "Letter title", name: "name", widget: "string" }
          - { label: "Letter document", name: "path", widget: "file" }
